apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      release: prometheus
  template:
    metadata:
      labels:
        release: prometheus
    spec:
      containers:
      - name: api-server-site
        image: 78220b880424
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 30000
    targetPort: 30000
    nodePort: 30001